In [12]:
import numpy as np
import pandas as pd

In [13]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [14]:
df = pd.read_csv(r"C:\Users\divya\OneDrive\DS\EDA\covid_toy.csv")

In [15]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [16]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [18]:
X_train

    age  gender  fever   cough       city
72   83  Female  101.0    Mild    Kolkata
82   24    Male   98.0    Mild    Kolkata
52   47  Female  100.0  Strong  Bangalore
10   75  Female    NaN    Mild      Delhi
46   19  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
19   42  Female    NaN  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
40   49  Female  102.0    Mild      Delhi
65   69  Female  102.0    Mild  Bangalore
64   42    Male  104.0    Mild     Mumbai

[80 rows x 5 columns]

## 1. Aam Zindagi

In [19]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [20]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [21]:
from sklearn.preprocessing import OneHotEncoder

# One Hot Encoding
ohe = OneHotEncoder(
    drop='first',
    sparse_output=False
)

# Train Data
X_train_gender_city = ohe.fit_transform(
    X_train[['gender', 'city']]
)

# Test Data
X_test_gender_city = ohe.transform(
    X_test[['gender', 'city']]
)

# Shape
print(X_train_gender_city.shape)

(80, 4)

In [22]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [23]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

## Mentos Zindagi

In [24]:
from sklearn.compose import ColumnTransformer

In [32]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [33]:
transformer.fit_transform(X_train).shape

(80, 7)

In [34]:
transformer.transform(X_test).shape

(20, 7)

In [35]:
X_train_transformed

array([[ 83.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 24.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 47.        , 100.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 75.        , 100.67123288,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 19.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 82.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 34.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 73.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 49.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 16.        , 103.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 81.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 70.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 38.        , 100.67123288,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 74.        , 102.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [  8.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 71.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 42.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 65.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 11.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 34.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 25.        ,  99.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 60.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 19.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 84.        , 100.67123288,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 12.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 60.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 22.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 20.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 59.        ,  99.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 24.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 50.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 15.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 64.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 81.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 26.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 65.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 31.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 54.        , 104.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 25.        , 104.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 68.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 64.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 47.        , 101.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 46.        , 103.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 20.        , 102.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 14.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 55.        , 100.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 82.        , 100.67123288,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 27.        , 100.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 72.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 51.        , 104.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 10.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 34.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [  6.        , 104.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 69.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 40.        ,  98.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 18.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  5.        , 102.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 20.        , 100.67123288,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 33.        , 102.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 73.        , 103.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 64.        , 102.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 80.        ,  98.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 38.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 71.        , 100.67123288,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 19.        , 100.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 49.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 17.        , 104.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 27.        , 100.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 80.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 69.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 14.        , 101.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 65.        ,  99.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 66.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [  5.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 23.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 42.        , 100.67123288,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 75.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 49.        , 102.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 69.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 42.        , 104.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ]])